apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rosf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rosf
    app.kubernetes.io/part-of: test-app-migr
  name: test-component-rosf
  namespace: build-e2e-hacbs-papc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-rosf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-rosf
    spec:
      containers:
      - image: quay.io/psturc/test-images:daaee963fbd24d4d953dc9bc7b64d34e
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
